version: '3.8'

services:
  app:
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: app
    working_dir: /app
    ports:
      - 8080:8080
    command: php -S 0.0.0.0:8080 -t ./public
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"

  fake_server:
    volumes:
      - ./fakeserver:/fakeserver
    image: node:latest
    container_name: fake_server
    working_dir: /fakeserver
    ports:
      - 3000:3000
    command: sh -c "npm install -g json-server && json-server --host 0.0.0.0 --watch db.json"