version: '3.8'

services:
  app:
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: app
    working_dir: /app
    ports:
      - 8080:8080
    command: php -S 0.0.0.0:8080 -t ./public
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"